channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake-minimal >=5.24.1
  - jinja2 =2.11
  - networkx =2.5
  - matplotlib =3.3
  - graphviz
  - pandas
  # - bcftools
  # - samtools
  # - bwa
  # - pysam

