channels:
  - bioconda
  - conda-forge
dependencies:
  - snakemake
  # - jinja2 =2.11
  # - networkx =2.5
  # - matplotlib =3.3
  # - graphviz
  - pip
  # - pandas
  # - sqlalchemy
  #- img2dataset
  # - tqdm
  # - art
  # - bcftools
  # - samtools
  # - bwa
  # - pysam

