#!/bin/bash
#read -t 0

#export data_dir="csvs"

export all=false
export min=1
export max=10
# export in=test

while getopts i:o:s:e:a: flag
do
    case "${flag}" in
        i) in=${OPTARG};;
        o) out=${OPTARG};;
        s) min=${OPTARG};;
        e) max=${OPTARG};;
        a) all=${OPTARG};;
    esac
done

if [ $all == "false" ]
then
  python scripts/ImgDownload.py --start_index $min --end_index $max --input_folder $in --data_dir $out
else
  python scripts/ImgDownload.py --start_index $min --end_index $max --input_folder $in --data_dir $out --all_data $all
fi
